### ISSUE TITLE
Error en condicional

### ISSUE THREAD

**Issue by Nagochi1** [jgaleano2018/PytoCocinasMedellinMauricio#1]
https://github.com/jgaleano2018/PytoCocinasMedellinMauricio/blob/d0985058f48f42c804036763cbb9b58c799d1db1/src/com/bancodebogota/fdm/cocinasmedellin/Ingrediente.java#L68

Falta comillas dobles en Si y No.

**Comment by jgaleano2018** [comment]
cambios realizados
