### ISSUE TITLE
Variable nombre

### ISSUE THREAD

**Issue by Nagochi1** [jgaleano2018/PytoCocinasMedellinMauricio#2]
https://github.com/jgaleano2018/PytoCocinasMedellinMauricio/blob/d0985058f48f42c804036763cbb9b58c799d1db1/src/com/bancodebogota/fdm/cocinasmedellin/Solido.java#L19

La variable nombre está declarada como int y no como string, por lo tanto no compila. Además esta variable la hereda de la clase Ingrediente.

**Comment by jgaleano2018** [comment]
Se soluciono el incidente de la clase solido.java.
